# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 05:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LanCenter', '0003_stockdetalle_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='stock',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='LanCenter.stock'),
            preserve_default=False,
        ),
    ]
