# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LanCenter', '0004_cuenta_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='totalentrega',
            field=models.FloatField(verbose_name='Total Entregado'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set([('usuario', 'fecha')]),
        ),
    ]
