# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 03:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LanCenter', '0005_auto_20171022_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='genero',
        ),
    ]
